[jupyter]
cmd = "jupyter-lab"
dir = "/home/doug/work"
[jupyter.env]
XLA_PYTHON_CLIENT_PREALLOCATE = "false"

[llama]
cmd = "python -m oneping server --port=8012"
dir = "/home/doug/mlai/mec"

[echo]
cmd = "echo"
dir = "/home/doug/mlai/mec"
